export enum OrderTypeEnum {
  LIMIT = 'LIMIT',
  MARKET = 'MARKET',
  STOP_MARKET = 'STOP_MARKET',
  TAKE_PROFIT_MARKET = 'TAKE_PROFIT_MARKET',
  TRIGGER_LIMIT = 'TRIGGER_LIMIT',
  TRIGGER_MARKET = 'TRIGGER_MARKET',
}
